services:
  flood:
    hostname: flood
    image: jesec/flood
    restart: unless-stopped
    ports:
      - 0.0.0.0:3001:3001
    command: --port 3001 --allowedpath /data
    environment:
      - HOME=/config
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/${USER}/config:/config
      - ${PATH_MEDIA}:/data

  rtorrent:
    hostname: rtorrent
    image: jesec/rtorrent
    restart: unless-stopped
    ports:
      - 0.0.0.0:4501:4501
    command: -o network.port_range.set=4501-4501,system.daemon.set=true
    environment:
      - HOME=/config
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/${USER}/config:/config
      - ${PATH_MEDIA}:/data

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    network_mode: "host"
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/${USER}/config/jackett:/config
      - /etc/localtime:/etc/localtime:ro

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    network_mode: "host"
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/${USER}/config/sonarr:/config
      - ${PATH_MEDIA}:/data

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    network_mode: "host"
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/${USER}/config/radarr:/config
      - ${PATH_MEDIA}:/data

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: "host"
    ports:
      - "${PORT:-8191}:8191"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - /home/${USER}/config/overseerr:/app/config
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - /home/${USER}/config/plex:/config
      - ${PATH_MEDIA}:/data
    restart: unless-stopped

  webserver:
    image: nginx:latest
    volumes:
    - ./templates:/etc/nginx/templates
    - ./nginx/proxy_params:/etc/nginx/proxy_params
    ports:
    - "80:80"
    - "443:443"
    environment:
    - NGINX_HOSTNAME=${HOSTNAME}
